services:
  frontend:
    depends_on:
      - backend
      - keyrock
    build: ./client
    networks:
      default:
        ipv4_address: 172.18.1.2
    ports:
      - 3000:3000
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001/api
    volumes:
      - ./client:/app
  
  backend:
    depends_on:
      - database
      - orion
    build: ./server
    networks:
      default:
        ipv4_address: 172.18.1.3
    ports:
      - 3001:3001
    expose:
      - "3001"
    environment: 
      - DS_URL=http://datastorage:27018/api
      - DB_URL=mongodb://database/cloud-app
      - KEYROCK_URL=http://keyrock:3005
      - ORION_URL=http://orion:1026
      - ORION_PROXY_URL=http://orion-proxy:1027
      - DSS_PROXY_URL=http://dss-proxy:1027/api
      - CLIENT_ID=d477b5b5-e253-44e8-9308-990c18cc6ed8
      - CLIENT_SECRET=5f26d98c-7942-48fa-8fbf-1cc14001a3a0
    volumes:
      - ./server:/app
    command: ["sh", "docker-entrypoint.sh"]
    
  datastorage:
    depends_on:
      - database
    build: ./data-storage
    networks:
      default:
        ipv4_address: 172.18.1.4
    ports:
      - 27018:27018
    environment:
      - DB_URL=mongodb://database/cloud-app
      - KEYROCK_URL=http://keyrock:3005
    command: ["sh", "docker-entrypoint.sh"]
    volumes:
      - ./data-storage:/app

  database:
    image: mongo:6.0
    networks:
      default:
        ipv4_address: 172.18.1.7
    ports: 
      - 27019:27017
    volumes:
      - ./dss-data:/data/db

  keyrock:
    image: fiware/idm:8.3.0
    hostname: keyrock
    networks:
      default:
        ipv4_address: 172.18.1.5
    depends_on:
      - mysql-db
    ports:
      - 3005:3005
      - 3443:3443
    environment:
      - "DEBUG=idm:*"
      - "IDM_DB_HOST=mysql-db"
      - "IDM_DB_PASS=mypassword"
      - "IDM_DB_USER=root"
      - "IDM_PORT=3005"
      - "IDM_HOST=http://localhost:3005"
      - "IDM_HTTPS_ENABLED=false"
      - "IDM_HTTPS_PORT=3443"
      - "IDM_ADMIN_USER=admin"
      - "IDM_ADMIN_EMAIL=admin@test.com"
      - "IDM_ADMIN_PASS=1234"
      - IDM_CSP_FORM_ACTION=*
    
  mysql-db:
    restart: always
    image: mysql:8.0
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      default:
        ipv4_address: 172.18.1.6
    environment:
      - "MYSQL_ROOT_PASSWORD=mypassword"
      - "MYSQL_ROOT_HOST=172.18.1.5" # Allow Keyrock to access this database
    volumes:
      - ./keyrock-data:/var/lib/mysql

  mongo-orion:
    image: mongo:4.4
    networks:
      default:
        ipv4_address: 172.18.1.8
    command: --nojournal
    volumes:
      - ./orion-data:/data/db
  
  orion:
    image: fiware/orion
    networks:
      default:
        ipv4_address: 172.18.1.9
    links:
      - mongo-orion
    ports:
      - "1026:1026"
    command: -dbhost mongo-orion

  orion-proxy:
    image: fiware/pep-proxy
    hostname: orion-proxy
    networks:
        default:
            ipv4_address: 172.18.1.10
    depends_on:
        - keyrock
    ports:
        - "1027:1027"
    expose:
        - "1027"
    environment:
        - PEP_PROXY_APP_HOST=orion
        - PEP_PROXY_APP_PORT=1026
        - PEP_PROXY_PORT=1027
        - PEP_PROXY_IDM_HOST=keyrock
        - PEP_PROXY_HTTPS_ENABLED=false
        - PEP_PROXY_AUTH_ENABLED=false
        - PEP_PROXY_IDM_SSL_ENABLED=false
        - PEP_PROXY_IDM_PORT=3005
        - PEP_PROXY_APP_ID=d477b5b5-e253-44e8-9308-990c18cc6ed8
        - PEP_PROXY_USERNAME=pep_proxy_d50b3c68-22be-4275-bd30-9c468ddf1ae5
        - PEP_PASSWORD=pep_proxy_892d5e90-4ae4-4c5e-ae1c-7ed8d7580cc6
        - PEP_PROXY_PDP=idm
        - PEP_PROXY_MAGIC_KEY=1234

  dss-proxy:
    image: fiware/pep-proxy
    hostname: dss-proxy
    networks:
        default:
            ipv4_address: 172.18.1.11
    depends_on:
        - keyrock
    ports:
        - "1030:1027"
    expose:
      - "1030"
    environment:
        - PEP_PROXY_APP_HOST=datastorage
        - PEP_PROXY_APP_PORT=27018
        - PEP_PROXY_PORT=1027
        - PEP_PROXY_IDM_HOST=keyrock
        - PEP_PROXY_HTTPS_ENABLED=false
        - PEP_PROXY_AUTH_ENABLED=false
        - PEP_PROXY_IDM_SSL_ENABLED=false
        - PEP_PROXY_IDM_PORT=3005
        - PEP_PROXY_APP_ID=d477b5b5-e253-44e8-9308-990c18cc6ed8
        - PEP_PROXY_USERNAME=pep_proxy_d50b3c68-22be-4275-bd30-9c468ddf1ae5
        - PEP_PASSWORD=pep_proxy_892d5e90-4ae4-4c5e-ae1c-7ed8d7580cc6
        - PEP_PROXY_PDP=idm
        - PEP_PROXY_MAGIC_KEY=1234
        


networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

